version: '3'

services:
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    volumes:
      - country_search:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - country_search_net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER} -d ${NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: country_search
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${NAME}
      SPRING_DATASOURCE_USERNAME: ${USER}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
    networks:
      - country_search_net
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      
  frontend:
    image: country_search_frontend
    container_name: frontend
    networks:
      - country_search_net
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db
volumes:
  country_search:


networks:
  country_search_net:
